# Generated by Django 4.1.1 on 2022-09-23 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecApp', '0003_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='u_id',
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
