# Generated by Django 4.1.1 on 2022-09-23 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecApp', '0004_remove_medico_u_id_medico_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
                ('auxiliar', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
