# Generated by Django 4.1.1 on 2022-09-23 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecApp', '0005_enfermero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parentezco', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='registro',
            field=models.CharField(default='RM000000001', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eps', models.CharField(max_length=20)),
                ('admision', models.DateField()),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hecApp.familiar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
