# Generated by Django 4.1.1 on 2022-09-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecApp', '0006_familiar_medico_registro_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='parentezco',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oximetria', models.JSONField()),
                ('f_respiratoria', models.JSONField()),
                ('f_cardiaca', models.JSONField()),
                ('temperatura', models.JSONField()),
                ('presion_arterial', models.JSONField()),
                ('glicemias', models.JSONField()),
                ('diagnostico', models.TextField()),
                ('cuidados', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hecApp.paciente')),
            ],
        ),
    ]
