# Generated by Django 4.1.1 on 2022-09-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecApp', '0007_alter_familiar_parentezco_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='familiar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hecApp.familiar'),
        ),
    ]
