# Generated by Django 4.1.1 on 2022-09-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hecApp', '0008_alter_paciente_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='familiar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hecApp.familiar'),
        ),
    ]
