from .enfermeroSerializer import EnfermeroSerializer
from .familiarSerializer import FamiliarSerializer
from .historiaSerializer import HistoriaSerializer
from .medicoSerializer import MedicoSerializer
from .pacienteSerializer import PacienteSerializer
from .rolSerializer import RolSerializer
from .usuarioSerializer import UsuarioSerializer