from .rolView import RolListCreateView, RolRetrieveDestroyView
from .landingView import LandingView
from .usuarioView import UsuarioListView, UsuarioRetrieveUpdateDestroyView
from .medicoView import MedicoListCreateView, MedicoRetrieveUpdateView
from .enfermeroView import EnfermeroListCreateView, EnfermeroRetrieveUpdateView